#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-PDF-API2
Version  : 2.043
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.043.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.043.tar.gz
Summary  : 'Create, modify, and examine PDF files'
Group    : Development/Tools
License  : LGPL-2.1
Requires: perl-PDF-API2-license = %{version}-%{release}
Requires: perl-PDF-API2-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Font::TTF)
BuildRequires : perl(Font::TTF::Font)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Test::Memory::Cycle)

%description
This archive contains the distribution PDF-API2,
version 2.043:
Create, modify, and examine PDF files

%package dev
Summary: dev components for the perl-PDF-API2 package.
Group: Development
Provides: perl-PDF-API2-devel = %{version}-%{release}
Requires: perl-PDF-API2 = %{version}-%{release}

%description dev
dev components for the perl-PDF-API2 package.


%package license
Summary: license components for the perl-PDF-API2 package.
Group: Default

%description license
license components for the perl-PDF-API2 package.


%package perl
Summary: perl components for the perl-PDF-API2 package.
Group: Default
Requires: perl-PDF-API2 = %{version}-%{release}

%description perl
perl components for the perl-PDF-API2 package.


%prep
%setup -q -n PDF-API2-2.043
cd %{_builddir}/PDF-API2-2.043

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-PDF-API2
cp %{_builddir}/PDF-API2-2.043/LICENSE %{buildroot}/usr/share/package-licenses/perl-PDF-API2/1dacddb36ccf9896e218bcce6279186eea834b88
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/PDF::API2.3
/usr/share/man/man3/PDF::API2::Annotation.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Array.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Bool.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Dict.3
/usr/share/man/man3/PDF::API2::Basic::PDF::File.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Filter.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Name.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Null.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Number.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Objind.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Page.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Pages.3
/usr/share/man/man3/PDF::API2::Basic::PDF::String.3
/usr/share/man/man3/PDF::API2::Basic::PDF::Utils.3
/usr/share/man/man3/PDF::API2::Content.3
/usr/share/man/man3/PDF::API2::Lite.3
/usr/share/man/man3/PDF::API2::NamedDestination.3
/usr/share/man/man3/PDF::API2::Outline.3
/usr/share/man/man3/PDF::API2::Page.3
/usr/share/man/man3/PDF::API2::Resource.3
/usr/share/man/man3/PDF::API2::Resource::BaseFont.3
/usr/share/man/man3/PDF::API2::Resource::CIDFont.3
/usr/share/man/man3/PDF::API2::Resource::CIDFont::CJKFont.3
/usr/share/man/man3/PDF::API2::Resource::CIDFont::TrueType.3
/usr/share/man/man3/PDF::API2::Resource::ColorSpace.3
/usr/share/man/man3/PDF::API2::Resource::ColorSpace::Indexed::ACTFile.3
/usr/share/man/man3/PDF::API2::Resource::ColorSpace::Separation.3
/usr/share/man/man3/PDF::API2::Resource::ExtGState.3
/usr/share/man/man3/PDF::API2::Resource::Font::BdFont.3
/usr/share/man/man3/PDF::API2::Resource::Font::CoreFont.3
/usr/share/man/man3/PDF::API2::Resource::Font::SynFont.3
/usr/share/man/man3/PDF::API2::Resource::XObject.3
/usr/share/man/man3/PDF::API2::Resource::XObject::Form.3
/usr/share/man/man3/PDF::API2::Resource::XObject::Form::BarCode.3
/usr/share/man/man3/PDF::API2::Resource::XObject::Form::BarCode::code128.3
/usr/share/man/man3/PDF::API2::Resource::XObject::Image.3
/usr/share/man/man3/PDF::API2::Resource::XObject::Image::TIFF.3
/usr/share/man/man3/PDF::API2::ViewerPreferences.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-PDF-API2/1dacddb36ccf9896e218bcce6279186eea834b88

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Annotation.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Array.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Bool.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Dict.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/File.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter/ASCII85Decode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter/ASCIIHexDecode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter/FlateDecode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter/LZWDecode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Filter/RunLengthDecode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Literal.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Name.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Null.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Number.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Objind.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Page.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Pages.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/String.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Basic/PDF/Utils.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Content.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Content/Text.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Lite.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Matrix.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/NamedDestination.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Outline.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Outlines.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Page.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/BaseFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont/adobemingstdlightacro.data
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont/adobemyungjostdmediumacro.data
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont/adobesongstdlightacro.data
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont/kozgopromediumacro.data
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CJKFont/kozminproregularacro.data
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CMap/japanese.cmap
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CMap/korean.cmap
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CMap/simplified.cmap
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/CMap/traditional.cmap
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/TrueType.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/CIDFont/TrueType/FontFile.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/DeviceN.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/Indexed.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/Indexed/ACTFile.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/Indexed/Hue.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/Indexed/WebColor.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ColorSpace/Separation.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Colors.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/ExtGState.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/BdFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/bankgothic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/courier.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/courierbold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/courierboldoblique.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/courieroblique.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/georgia.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/georgiabold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/georgiabolditalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/georgiaitalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/helvetica.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/helveticabold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/helveticaboldoblique.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/helveticaoblique.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/symbol.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/timesbold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/timesbolditalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/timesitalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/timesroman.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/trebuchet.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/trebuchetbold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/trebuchetbolditalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/trebuchetitalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/verdana.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/verdanabold.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/verdanabolditalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/verdanaitalic.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/webdings.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/wingdings.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/CoreFont/zapfdingbats.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/Postscript.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Font/SynFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Glyphs.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/PaperSizes.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Pattern.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/Shading.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/UniFont.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode/codabar.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode/code128.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode/code3of9.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode/ean13.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/BarCode/int2of5.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Form/Hybrid.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/GD.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/GIF.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/JPEG.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/PNG.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/PNM.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/TIFF.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/XObject/Image/TIFF/File.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Resource/uniglyph.txt
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/UniWrap.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Util.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/ViewerPreferences.pm
/usr/lib/perl5/vendor_perl/5.34.0/PDF/API2/Win32.pm
